/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#bd6efe",
        "tertiary-fixed-dim": "#ff75a4",
        "secondary-container": "#0634c7",
        "on-surface": "#e9e2f8",
        "outline": "#787386",
        "on-secondary-container": "#cbd1ff",
        "secondary-fixed": "#c8cfff",
        "on-primary-fixed-variant": "#450073",
        "tertiary-container": "#ff2d8b",
        "tertiary-fixed": "#ff8eb1",
        "surface-bright": "#2e2941",
        "error-container": "#a70138",
        "background": "#0f0c1b",
        "on-secondary": "#001564",
        "primary": "#d095ff",
        "primary-fixed": "#c782ff",
        "surface-variant": "#272339",
        "on-primary": "#490078",
        "surface-dim": "#0f0c1b",
        "on-tertiary": "#470021",
        "inverse-primary": "#8534c4",
        "outline-variant": "#4a4557",
        "primary-container": "#c782ff",
        "secondary-fixed-dim": "#b6c0ff",
        "surface-container-lowest": "#000000",
        "on-secondary-fixed-variant": "#193ece",
        "on-tertiary-fixed-variant": "#76003a",
        "on-primary-fixed": "#000000",
        "on-secondary-fixed": "#002496",
        "tertiary": "#ff6a9f",
        "on-error-container": "#ffb2b9",
        "surface-container-low": "#141122",
        "error-dim": "#d73357",
        "surface-container-highest": "#272339",
        "on-tertiary-fixed": "#380018",
        "on-error": "#490013",
        "inverse-surface": "#fdf7ff",
        "secondary-dim": "#4967f4",
        "on-tertiary-container": "#000000",
        "on-primary-container": "#38005e",
        "inverse-on-surface": "#575365",
        "surface": "#0f0c1b",
        "surface-container-high": "#211d31",
        "on-surface-variant": "#aea8bd",
        "tertiary-dim": "#ff6a9f",
        "on-background": "#e9e2f8",
        "secondary": "#8397ff",
        "surface-tint": "#d095ff",
        "surface-container": "#1b1729",
        "error": "#ff6e84",
        "primary-dim": "#c57eff"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
